version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: your-username
      POSTGRES_PASSWORD: your-password
      POSTGRES_DB: your-database-name
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:latest
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: your-username
      MONGO_INITDB_ROOT_PASSWORD: your-password
    ports:
      - "27017:27017"

  mongodbNA:
    image: mongo:latest
    container_name: mongo-db-na
    environment:
      MONGO_INITDB_ROOT_USERNAME: your-username
      MONGO_INITDB_ROOT_PASSWORD: your-password
    ports:
      - "27018:27017"